### ISSUE TITLE
Unsupported config option for services: 'quetre'

### ISSUE THREAD

**Issue by ghost** [PussTheCat-org/docker-quetre-quay#2]
I get this error that isn't very helpful from ``docker-compose up -d``:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'quetre'
```
Here's my config file:
```
services:
  quetre:
    container_name: quetre
    image: quay.io/pussthecatorg/quetre:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000" # Replace with "3000:3000" if you don't use a reverse proxy
    environment:
      - "NODE_ENV=production"
      - "PORT=4000"
```
Can you figure out what's wrong with it?
